runtime: python311

handlers:
  # Serve the main page
  - url: /
    static_files: index.html
    upload: index.html

  # Serve all other static files (CSS, JS, images, etc.)
  - url: /(.*)
    static_files: \1
    upload: (.*)
